# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  install-packages:
    docker:
     - image: cimg/node:17.3.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unpluggedgp -
      - persist_to_workspace:
          root: ~/
          paths: .

  build-app-to-dist:
    docker:
      - image: cimg/node:17.3.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: 'Build app to dist'
          command: 'yarn build'

  type-check:
    docker:
      - image: cimg/node:17.3.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: 'Check types'
          command: 'yarn check-types'

  test:
    docker:
      - image: cimg/node:17.3.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: 'Test app'
          command: 'yarn test'

workflows:
  deployment:
    jobs:
      - install-packages
      - type-check:
          requires:
            - install-packages
      - test:
          requires:
            - install-packages
      - build-app-to-dist:
          requires:
            - install-packages
            - test
            - type-check